### PR TITLE
Fix: Global option values ignored when args provided

### LINKED ISSUE #86: Global option values ignored when args provided
Global options are ignored when additional command line arguments are also provided.

Using the test harness below, I get the following results.

#### 1. Without extra arguments provided ✅ 

In this scenario without extra arguments provided, the command correctly uses the provided global option value.

```sh
./command.rb experiment --config config-value
args:   []
config: "config-value"
```

#### 2. With extra arguments provided after the global config :x:

However with arguments provided after the configuration value, the command incorrectly falls back to the default value.

```sh
./command.rb experiment --config config-value arg1 arg2
args:   ["arg1", "arg2"]
config: "default"
```

#### 3. With extra arguments provided before the global config :x:

Similarly with arguments provided before the configuration value, the command incorrectly falls back to the default value.

```sh
./command.rb experiment arg1 arg2 --config config-value
args:   ["arg1", "arg2"]
config: "default"
```

#### `command.rb` test harness

```ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'commander'

class MyApplication
  include Commander::Methods

  def run
    program :name, 'Example with global option'
    program :description, 'Example with global option'
    program :version, '1.0.0'
    global_option '-c', '--config CONFIG', String, 'A global option'

    command :experiment do |c|
      c.action do |args, options|
        options.default {config: 'default'}
        say "args:   #{args.inspect}"
        say "config: #{options.config.inspect}"
      end
    end

    run!
  end
end

MyApplication.new.run if $0 == __FILE__
```

### PR DESCRIPTION
**Pull request by orien**
### Context

As detailed in #86, global options are ignored when command specific options or arguments are provided.

### Proposed Solution

Separate the global options from the command specific options. This prevents the global options from being cleared when the command specific options are parsed.

Fixes #86.

### CODE REVIEW

File: spec/command_spec.rb [hunk 1]
```diff
@@ -164,6 +164,33 @@
         end
         @command.run '--interval', '15'
       end
+
+      describe 'given a global option' do
```
Comment (ggilder) [inline spec/command_spec.rb]: This looks great! Could you also add a "integration" type spec to `runner_spec.rb`? I took a quick stab here: https://github.com/commander-rb/commander/commit/0d8cfe47a6e6e4aa463e610bbfd4e044673d46b8 

Feel free to pull in that commit or rewrite as you see fit. Thanks!

Comment (orien) [reply spec/command_spec.rb]: Awesome! I've merged that in.

**Comment by ggilder** [comment]
Just released in v4.5.1. Thanks for fixing this!
