### PR TITLE
Use --help after command and argument

### LINKED ISSUE #94: Regression: `--help` no longer works anywhere on the command line
Given a sample program:

```ruby
require 'commander/import'

program :name, 'Name'
program :version, '0.1'
program :description, 'Issue with Global Option parsing.'

command :cmd do |c|
  c.action do
    puts 'Success'
  end
end
```

Previously you could use the global `--help` anywhere on the line but now you can't. This used to provide the help for `cmd`, but no longer does:

```
$ ruby foo.rb cmd a --help
invalid command. Use --help for more information
```

Seems like a recent regression.

### PR DESCRIPTION
**Pull request by orien**
#### Context

It is reported in #94 that using `--help` after a command name and command argument does not work.

```
$ mycli command-name command-arg --help
invalid command. Use --help for more information
```

Investigation finds the `help` command is assuming the the command name is all the arguments joined together.

https://github.com/commander-rb/commander/blob/b8abd42153118ca9fdc02affeb9f3aab61cda5a2/lib/commander/runner.rb#L307

#### Change

Fix #94 by changing the line in question to ignore the command argument when searching for command name. Just take the longest valid command name found in the arguments.

#### Considerations

This also changes the behaviour of the help command in its alternate form. This will ignore the argument and provide the documentation for the specified command, where previously it would give an error message.

```
mycli help command-name command-arg
```

### CODE REVIEW

File: lib/commander/runner.rb [hunk 1]
```diff
@@ -304,7 +304,7 @@ def create_default_commands
           if args.empty?
             say help_formatter.render
           else
-            command = command args.join(' ')
+            command = command(valid_command_names_from(*args.dup).sort.last)
```
Comment (orien) [inline lib/commander/runner.rb]: This new logic was copied from `command_name_from_args` method.

https://github.com/commander-rb/commander/blob/b8abd42153118ca9fdc02affeb9f3aab61cda5a2/lib/commander/runner.rb#L241-L243

There's undoubtedly an opportunity to refactor to DRY this up. Unfortunately, I haven't the time today.

Comment (orien) [reply lib/commander/runner.rb]: I've extracted a new method to DRY this up.

File: lib/commander/runner.rb [hunk 2]
```diff
@@ -237,9 +237,18 @@ def active_command
...
-      @__command_name_from_args ||= (valid_command_names_from(*@args.dup).sort.last || @default_command)
+      @__command_name_from_args ||= (longest_valid_command_name_from(@args) || @default_command)
+    end
+
+    ##
+    # Attempts to locate a command name from within the provided arguments.
+    # Supports multi-word commands, using the largest possible match.
+
+    private def longest_valid_command_name_from(args)
+      valid_command_names_from(*args.dup).max
```
Comment (orien) [inline lib/commander/runner.rb]: Extract a new method to keep things DRY.

I've made a small optimisation change here. I predict `max` will be faster than `stort.last` as it'll get the same result without creating a new `Array`.

```diff
- valid_command_names_from(*args.dup).sort.last
+ valid_command_names_from(*args.dup).max
```

File: spec/runner_spec.rb [hunk 3]
```diff
@@ -484,6 +484,10 @@
       expect(run('test', '--help')).to eq("Implement help for test here\n")
     end
 
+    it 'can be used after the command and command arguments' do
+      expect(run('test', 'command-arg', '--help')).to eq("Implement help for test here\n")
+    end
```
Comment (ggilder) [inline spec/runner_spec.rb]: Let's also add a similar test for the `help test command-arg` scenario

Comment (ggilder) [reply spec/runner_spec.rb]: And just to be thorough, a test for multi-word commands would be nice — something like the following:

```ruby
it 'can be used before a multi-word command with command arguments' do
  expect(
    run('help', 'module', 'install', 'command-arg') do
      command('module install') { |c| c.when_called { say 'whee!' } }
    end
  ).to eq("Implement help for module install here\n")
end
```

Comment (orien) [reply spec/runner_spec.rb]: Added in [ea4d912](https://github.com/commander-rb/commander/compare/b6381fc67faef3872c44e0e0f19fd030d6a67ea6..ea4d912a58ec5332fbd605a1e0d91bf3230f4160).
